platform :osx, '10.13'

target 'Storybook Packager' do

  use_frameworks!

  # Software update framework
  pod 'Sparkle', '~> 1.22'

  # testing for Internet availability
  pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git'

end
