platform :osx, '10.13'

target 'Storybook Packager' do

  use_frameworks!

  # Storybook+ XML Parser
  pod 'sbplus-xml-parser', :git => 'https://github.com/oel-mediateam/sbplus-xml-parser.git'

  # Software update framework
  pod 'Sparkle'

  # testing for Internet availability
  pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift.git'

end
