# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'Storybook Packager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Storybook Packager

  # Software update framework
  pod 'Sparkle'

  # testing for Internet availability
  pod 'Reachability'

end
